-- =============================================================================
-- Migration: 0010_orders
-- Description: Order records per tenant. Stores full address and financial
--              snapshots at order time (decoupled from live addresses/prices).
--              order_number generated by Edge Function, unique per tenant.
--              payment_status is synced automatically by the payments trigger.
-- =============================================================================

CREATE TABLE orders (
  id                   uuid            PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid            NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  order_number         varchar(50)     NOT NULL,
  customer_id          uuid            REFERENCES customers(id) ON DELETE SET NULL,
  customer_name        varchar(200)    NOT NULL,
  customer_phone       varchar(20),
  customer_email       varchar(255),
  source               order_source    NOT NULL DEFAULT 'admin_created',
  status               order_status    NOT NULL DEFAULT 'pending',
  payment_method       payment_method  NOT NULL,
  payment_status       payment_status  NOT NULL DEFAULT 'pending',

  -- Address snapshot (copied from addresses at order time, immutable)
  shipping_street      varchar(255),
  shipping_city        varchar(100),
  shipping_state       varchar(100),
  shipping_postal_code varchar(20),
  shipping_country     varchar(100),
  shipping_notes       text,

  -- Financial snapshot (all values locked at order time)
  currency             varchar(10)     NOT NULL DEFAULT 'CZK',
  subtotal             numeric(10,2)   NOT NULL CHECK (subtotal >= 0),
  coupon_id            uuid            REFERENCES coupons(id) ON DELETE SET NULL,
  coupon_code          varchar(50),
  coupon_discount      numeric(10,2)   NOT NULL DEFAULT 0 CHECK (coupon_discount >= 0),
  vat_percentage       numeric(5,2)    NOT NULL DEFAULT 0 CHECK (vat_percentage >= 0),
  vat_amount           numeric(10,2)   NOT NULL DEFAULT 0 CHECK (vat_amount >= 0),
  delivery_fee         numeric(10,2)   NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
  grand_total          numeric(10,2)   NOT NULL CHECK (grand_total >= 0),

  -- Operational fields
  tracking_number      varchar(100),
  notes                text,
  cancelled_reason     text,
  created_by           uuid            REFERENCES staff_profiles(id) ON DELETE SET NULL,
  created_at           timestamptz     NOT NULL DEFAULT now(),
  updated_at           timestamptz     NOT NULL DEFAULT now(),

  -- order_number unique per tenant
  CONSTRAINT orders_tenant_number_key
    UNIQUE (tenant_id, order_number),

  -- cancelled_reason only allowed when status is 'cancelled'
  CONSTRAINT cancelled_reason_only_when_cancelled
    CHECK (cancelled_reason IS NULL OR status = 'cancelled')
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX idx_orders_tenant_id      ON orders (tenant_id);
CREATE INDEX idx_orders_customer_id    ON orders (customer_id);
CREATE INDEX idx_orders_status         ON orders (status);
CREATE INDEX idx_orders_payment_status ON orders (payment_status);
CREATE INDEX idx_orders_created_at     ON orders (created_at DESC);
CREATE INDEX idx_orders_source         ON orders (source);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- All staff roles can read orders within their tenant
CREATE POLICY "tenant_staff_read_orders"
ON orders FOR SELECT
USING (
  tenant_id = (auth.jwt() ->> 'tenant_id')::uuid
);

-- All staff roles can create orders within their tenant
CREATE POLICY "tenant_staff_insert_orders"
ON orders FOR INSERT
WITH CHECK (
  tenant_id = (auth.jwt() ->> 'tenant_id')::uuid
  AND auth.jwt() ->> 'role' IN ('admin', 'manager', 'staff')
);

-- All staff roles can update orders within their tenant
CREATE POLICY "tenant_staff_update_orders"
ON orders FOR UPDATE
USING (
  tenant_id = (auth.jwt() ->> 'tenant_id')::uuid
  AND auth.jwt() ->> 'role' IN ('admin', 'manager', 'staff')
);

-- Only admins can delete orders within their tenant
CREATE POLICY "tenant_admins_delete_orders"
ON orders FOR DELETE
USING (
  tenant_id = (auth.jwt() ->> 'tenant_id')::uuid
  AND auth.jwt() ->> 'role' = 'admin'
);
